### PR TITLE
build: Configure PR title validation

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/marketplace/actions/conventional-pr-title

#17

### CODE REVIEW

**Comment by pkazmier** [comment]
Thanks for the contribution @gliptak. You reference [conventional-pr-title](https://github.com/marketplace/actions/conventional-pr-title) in the PR description, but the workflow uses [action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request). Which one were you thinking of using? I'll take a look at both of them now as well.

**Comment by pkazmier** [comment]
They both use ultimately use the same parser it seems, but [action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request) seems to be more configurable. I'm assuming this is the one you landed on as well given it was the one used in the actual commit.

The only question I have is regarding the use of `pull_request_target` vs `pull_request`. It seems that the latter is safer in general to use as the credentials are read-only vs read-write. Thoughts?

```yaml
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
```

**Comment by gliptak** [comment]
@pkazmier thank you for your analysis. https://github.com/amannn/action-semantic-pull-request seemed to have been more popular

reading https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ `pull_request` might be better fit

here is a failing run https://github.com/gliptak/awsrun/actions/runs/4179413368/jobs/7239331269

**Review by pkazmier — CHANGES_REQUESTED** [review]
I think we should explicitly list the types like you had before. According to the [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request), the default activities only include `opened`, `reopened`, and `synchronize`. I think we should add `edited` in the list too, so the title is checked if the user modifies it. Thoughts?

**Comment by gliptak** [comment]
thank you for the review, updated

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

**Review by pkazmier — CHANGES_REQUESTED** [review]
I think you missed `reopened` as well. Thanks!

**Review by pkazmier — APPROVED** [review]

**Comment by pkazmier** [comment]
Thanks @gliptak. I've not really explored Github Actions yet, so your contributions have been much appreciated. It's also provided me the motivation to learn more about Actions.

**Pull request merged**
